arm_joint_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
  publish_rate: 20
arm_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
  publish_rate: 20
arm_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 150
controller_list:
  - name: arm_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
#dsr_joint1_position:
#  type: position_controllers/JointPositionController
#  joint: joint1
#  pid: {p: 500.0, i: 100.0, d: 200.0,  i_clamp: 500}

#dsr_joint2_position:
#  type: position_controllers/JointPositionController
#  joint: joint2
#  pid: {p: 500.0, i: 100.0, d: 250.0, i_clamp: 500}

#dsr_joint3_position:
#  type: position_controllers/JointPositionController
#  joint: joint3
#  pid: {p: 300.0, i: 20.0, d: 40.0, i_clamp: 500}

#dsr_joint4_position:
#  type: position_controllers/JointPositionController
#  joint: joint4
#  pid: {p: 100.0, i: 0.0, d: 40.0, i_clamp: 500}

#dsr_joint5_position:
#  type: position_controllers/JointPositionController
#  joint: joint5
#  pid: {p: 200.0, i: 20.0, d: 25.0, i_clamp: 500}

#dsr_joint6_position:
#  type: position_controllers/JointPositionController
#  joint: joint6
#  pid: {p: 300.0, i: 20.0, d: 25.0, i_clamp: 500}
